In [5]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Arrays

In [8]:
my_array = make_array(1, 2, 3, 4)

In [9]:
my_array

array([1, 2, 3, 4])

In [10]:
my_array * 2

array([2, 4, 6, 8])

In [11]:
my_array ** 2

array([ 1,  4,  9, 16])

In [12]:
my_array + 1

array([2, 3, 4, 5])

In [13]:
my_array # array is unchanged

array([1, 2, 3, 4])

In [14]:
len(my_array)

4

In [15]:
sum(my_array)

10

In [16]:
sum(my_array) / len(my_array)

2.5

In [17]:
np.average(my_array)

2.5

In [18]:
another = make_array(70, 60, 90, 80)

In [19]:
my_array + another

array([71, 62, 93, 84])

In [20]:
yet_another = make_array(5, 6, 7)

In [21]:
my_array + yet_another

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [22]:
tunas = make_array('bluefin', 'albacore', 'jim')
tunas

array(['bluefin', 'albacore', 'jim'], dtype='<U8')

In [23]:
tunas * 4

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U8'), dtype('<U8')) -> dtype('<U8')

In [24]:
tunas.item(0) # NOTE: indexing starts at 0!

'bluefin'

In [25]:
tunas.item(2)

'jim'

In [26]:
tunas.item(3)

IndexError: index 3 is out of bounds for axis 0 with size 3

## Columns of Tables are Arrays ##

In [29]:
nba = Table.read_table('nba_salaries.csv').relabeled(3, 'SALARY')
warriors = nba.where('TEAM', 'Golden State Warriors')

In [30]:
warriors

PLAYER            | POSITION | TEAM                  | SALARY
Klay Thompson     | SG       | Golden State Warriors | 15.501
Draymond Green    | PF       | Golden State Warriors | 14.2609
Andrew Bogut      | C        | Golden State Warriors | 13.8
Andre Iguodala    | SF       | Golden State Warriors | 11.7105
Stephen Curry     | PG       | Golden State Warriors | 11.3708
Jason Thompson    | PF       | Golden State Warriors | 7.00847
Shaun Livingston  | PG       | Golden State Warriors | 5.54373
Harrison Barnes   | SF       | Golden State Warriors | 3.8734
Marreese Speights | C        | Golden State Warriors | 3.815
Leandro Barbosa   | SG       | Golden State Warriors | 2.5
... (4 rows omitted)

In [31]:
warriors.select('SALARY')

SALARY
15.501
14.2609
13.8
11.7105
11.3708
7.00847
5.54373
3.8734
3.815
2.5
... (4 rows omitted)

In [32]:
warriors.column('SALARY')

array([15.501   , 14.26087 , 13.8     , 11.710456, 11.370786,  7.008475,
        5.543725,  3.873398,  3.815   ,  2.5     ,  2.008748,  1.270964,
        1.13196 ,  0.289755])

In [33]:
np.average(warriors.column('SALARY'))

6.72036692857143

In [34]:
raptors = nba.where('TEAM', 'Toronto Raptors')

In [35]:
np.average(warriors.column('SALARY')) - np.average(raptors.column('SALARY'))

2.3278598697479005

## Ranges ##

In [37]:
make_array(0, 1, 2, 3, 4, 5, 6)

array([0, 1, 2, 3, 4, 5, 6])

In [38]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [39]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [40]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [42]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

# Ways to Create a Table #

## Creating a Table from Scratch ##

In [43]:
streets = make_array('Bancroft', 'Durant', 'Channing', 'Haste')
streets

array(['Bancroft', 'Durant', 'Channing', 'Haste'], dtype='<U8')

In [44]:
Table()

In [45]:
southside = Table().with_column('Streets', streets)
southside

Streets
Bancroft
Durant
Channing
Haste

In [46]:
southside.with_column('Blocks from campus', np.arange(4))

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

In [47]:
southside

Streets
Bancroft
Durant
Channing
Haste

In [48]:
southside = southside.with_column('Blocks from campus', np.arange(4))
southside

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

In [49]:
Table().with_columns(
    'Streets', streets,
    'Blocks from campus', np.arange(4)
)

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

## Reading a Table from a File  ##

In [54]:
du_bois = Table.read_table('du_bois.csv')
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

In [58]:
du_bois.column('ACTUAL AVERAGE')

array([ 139.1 ,  249.45,  335.66,  433.82,  547.  ,  880.  , 1125.  ])

In [59]:
du_bois.column('FOOD')

array([0.43, 0.47, 0.43, 0.37, 0.31, 0.37, 0.29])

In [60]:
du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')

array([ 59.813 , 117.2415, 144.3338, 160.5134, 169.57  , 325.6   ,
       326.25  ])

In [61]:
food_dollars = du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')
du_bois.with_columns('Food $', food_dollars)

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS      | Food $
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR        | 59.813
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR        | 117.241
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR        | 144.334
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR        | 160.513
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25

In [62]:
du_bois.select('CLASS', 'ACTUAL AVERAGE', 'FOOD', 'Food $')

ValueError: The column "Food $" is not in the table. The table contains these columns: CLASS, ACTUAL AVERAGE, RENT, FOOD, CLOTHES, TAXES, OTHER, STATUS

In [63]:
food_dollars = du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')

du_bois = du_bois.with_columns('Food $', food_dollars)

du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS      | Food $
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR        | 59.813
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR        | 117.241
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR        | 144.334
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR        | 160.513
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25

In [64]:
du_bois.select('CLASS', 'ACTUAL AVERAGE', 'FOOD', 'Food $')

CLASS         | ACTUAL AVERAGE | FOOD | Food $
100-200       | 139.1          | 0.43 | 59.813
200-300       | 249.45         | 0.47 | 117.241
300-400       | 335.66         | 0.43 | 144.334
400-500       | 433.82         | 0.37 | 160.513
500-750       | 547            | 0.31 | 169.57
750-1000      | 880            | 0.37 | 325.6
1000 and over | 1125           | 0.29 | 326.25

In [65]:
du_bois.labels

('CLASS',
 'ACTUAL AVERAGE',
 'RENT',
 'FOOD',
 'CLOTHES',
 'TAXES',
 'OTHER',
 'STATUS',
 'Food $')

In [66]:
du_bois.num_rows

7

In [67]:
du_bois.num_columns

9